version: '3'
services:
  web:
    image: alpine
    container_name: demo_web
    volumes:
      - ./web/static:/static:z
      - ./common/config/web/web:/web:z
      - ./common/config/web/start.sh:/start.sh:z
    env_file:
      - ./common/config/web/env
    command: /bin/ash ./start.sh
  back1:
    image: alpine
    container_name: demo_back1
    volumes:
      - ./common/config/back1/back1:/back1:z
    entrypoint: ./back1
  back2:
    image: alpine
    container_name: demo_back2
    volumes:
      - ./common/config/back2/back2:/back2:z
    entrypoint: ./back2
  proxy:
    image: nginx
    container_name: demo_proxy
    env_file:
      - ./common/config/nginx/env
    volumes:
      - ./common/config/nginx/nginx.conf:/etc/nginx/nginx.conf:z
    ports:
      - 4443:4443

    