version: '3'
services:
  web:
    image: alpine
    container_name: demo_web
    volumes:
      - ./web/static:/static:z
      - ./common/config/web/web:/web:z
      - ./common/config/web/start.sh:/start.sh:z
      - ./common/config/web/healthcheck.sh:/usr/local/bin/healthcheck.sh:z
    env_file:
      - ./common/config/web/env
    command: chmod +x /usr/local/bin/healthcheck.sh && chmod +x ./web && apk add --no-cache curl && /bin/ash ./start.sh

  back1:
    image: alpine
    container_name: demo_back1
    volumes:
      - ./common/config/back1/back1:/back1:z
      - ./common/config/back1/healthcheck.sh:/usr/local/bin/healthcheck.sh:z
    command: chmod +x /usr/local/bin/healthcheck.sh && apk add --no-cache curl
    entrypoint: ./back1

  back2:
    image: alpine
    container_name: demo_back2 
    volumes:
      - ./common/config/back2/back2:/back2:z
      - ./common/config/back2/healthcheck.sh:/usr/local/bin/healthcheck.sh:z
    command: chmod +x /usr/local/bin/healthcheck.sh && apk add --no-cache curl
    entrypoint: ./back2

  proxy:
    image: nginx
    container_name: demo_proxy
    volumes:
      - ./common/config/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./common/config/nginx/healthcheck.sh:/usr/local/bin/healthcheck.sh:z
    command: chmod +x /usr/local/bin/healthcheck.sh && apt update && apt install curl -y
    ports:
      - 4443:4443